-- Foundation init wave 0

-- Shared enums only

CREATE SCHEMA IF NOT EXISTS "public";

CREATE TYPE "FoundationScopeType" AS ENUM ('PLATFORM', 'TENANT', 'BRAND', 'STORE', 'MARKET', 'PORTAL', 'USER', 'DEVICE', 'INTEGRATION');

CREATE TYPE "IdentitySubjectType" AS ENUM ('PLATFORM_USER', 'TENANT_USER', 'BRAND_USER', 'STORE_USER', 'EMPLOYEE', 'MEMBER', 'DEVICE', 'SERVICE_ACCOUNT');

CREATE TYPE "OrganizationNodeType" AS ENUM ('PLATFORM', 'TENANT', 'BRAND', 'REGION', 'STORE', 'DEPARTMENT', 'TEAM');

CREATE TYPE "PolicyEffect" AS ENUM ('ALLOW', 'DENY');

CREATE TYPE "ConfigValueType" AS ENUM ('JSON', 'STRING', 'NUMBER', 'BOOLEAN');

CREATE TYPE "SecretKind" AS ENUM ('API_KEY', 'ACCESS_TOKEN', 'REFRESH_TOKEN', 'PASSWORD', 'CERTIFICATE', 'PRIVATE_KEY', 'PUBLIC_KEY', 'WEBHOOK_SECRET');

CREATE TYPE "SecretProvider" AS ENUM ('DATABASE', 'VAULT', 'KMS', 'EXTERNAL');

CREATE TYPE "CertificateFormat" AS ENUM ('PEM', 'PFX', 'JKS');

CREATE TYPE "EventStatus" AS ENUM ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED', 'DEAD_LETTER');

CREATE TYPE "WebhookDeliveryStatus" AS ENUM ('PENDING', 'DELIVERED', 'FAILED', 'DEAD_LETTER');

CREATE TYPE "NotificationChannelType" AS ENUM ('EMAIL', 'SMS', 'PUSH', 'IN_APP', 'WEBHOOK', 'SOCIAL');

CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'FAILED', 'CANCELLED');

CREATE TYPE "EdgeNodeStatus" AS ENUM ('ONLINE', 'OFFLINE', 'DEGRADED', 'MAINTENANCE');

CREATE TYPE "EdgeSyncDirection" AS ENUM ('UPSTREAM', 'DOWNSTREAM', 'BIDIRECTIONAL');

CREATE TYPE "FileAssetKind" AS ENUM ('AVATAR', 'IMAGE', 'VIDEO', 'DOCUMENT', 'ARCHIVE', 'CERTIFICATE');

CREATE TYPE "OpenPlatformAppType" AS ENUM ('INTERNAL', 'ISV', 'PARTNER');

CREATE TYPE "QuotaPeriod" AS ENUM ('MINUTE', 'HOUR', 'DAY', 'MONTH');

CREATE TYPE "FeatureFlagStatus" AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED');

CREATE TYPE "RolloutStrategy" AS ENUM ('ALL', 'PERCENTAGE', 'ALLOW_LIST', 'SCOPE_MATCH');

CREATE TYPE "ApprovalStatus" AS ENUM ('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'SUPERSEDED');

CREATE TYPE "FoundationAlertAcknowledgementStatus" AS ENUM ('ACKED', 'MUTED');

CREATE TYPE "BackupStatus" AS ENUM ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED');

CREATE TYPE "RestoreStatus" AS ENUM ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED');

CREATE TYPE "PiiLevel" AS ENUM ('PUBLIC', 'INTERNAL', 'SENSITIVE', 'RESTRICTED');

CREATE TYPE "AiProvider" AS ENUM ('OPENAI', 'AZURE_OPENAI', 'ANTHROPIC', 'GEMINI', 'DEEPSEEK');

CREATE TYPE "AiExecutionStatus" AS ENUM ('PENDING', 'SUCCEEDED', 'FAILED', 'ESCALATED');
