"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.VenueResponseDto = void 0;
var swagger_1 = require("@nestjs/swagger");
var venue_entity_1 = require("../entities/venue.entity");
var VenueResponseDto = function () {
    var _a;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _name_decorators;
    var _name_initializers = [];
    var _name_extraInitializers = [];
    var _description_decorators;
    var _description_initializers = [];
    var _description_extraInitializers = [];
    var _address_decorators;
    var _address_initializers = [];
    var _address_extraInitializers = [];
    var _city_decorators;
    var _city_initializers = [];
    var _city_extraInitializers = [];
    var _province_decorators;
    var _province_initializers = [];
    var _province_extraInitializers = [];
    var _postalCode_decorators;
    var _postalCode_initializers = [];
    var _postalCode_extraInitializers = [];
    var _country_decorators;
    var _country_initializers = [];
    var _country_extraInitializers = [];
    var _latitude_decorators;
    var _latitude_initializers = [];
    var _latitude_extraInitializers = [];
    var _longitude_decorators;
    var _longitude_initializers = [];
    var _longitude_extraInitializers = [];
    var _type_decorators;
    var _type_initializers = [];
    var _type_extraInitializers = [];
    var _capacity_decorators;
    var _capacity_initializers = [];
    var _capacity_extraInitializers = [];
    var _area_decorators;
    var _area_initializers = [];
    var _area_extraInitializers = [];
    var _facilities_decorators;
    var _facilities_initializers = [];
    var _facilities_extraInitializers = [];
    var _openingHours_decorators;
    var _openingHours_initializers = [];
    var _openingHours_extraInitializers = [];
    var _contactPhone_decorators;
    var _contactPhone_initializers = [];
    var _contactPhone_extraInitializers = [];
    var _contactEmail_decorators;
    var _contactEmail_initializers = [];
    var _contactEmail_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _allowOnlineBooking_decorators;
    var _allowOnlineBooking_initializers = [];
    var _allowOnlineBooking_extraInitializers = [];
    var _bookingAdvanceHours_decorators;
    var _bookingAdvanceHours_initializers = [];
    var _bookingAdvanceHours_extraInitializers = [];
    var _cancellationPolicy_decorators;
    var _cancellationPolicy_initializers = [];
    var _cancellationPolicy_extraInitializers = [];
    var _pricing_decorators;
    var _pricing_initializers = [];
    var _pricing_extraInitializers = [];
    var _images_decorators;
    var _images_initializers = [];
    var _images_extraInitializers = [];
    var _createdBy_decorators;
    var _createdBy_initializers = [];
    var _createdBy_extraInitializers = [];
    var _ownerId_decorators;
    var _ownerId_initializers = [];
    var _ownerId_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _distance_decorators;
    var _distance_initializers = [];
    var _distance_extraInitializers = [];
    var _averageRating_decorators;
    var _averageRating_initializers = [];
    var _averageRating_extraInitializers = [];
    var _reviewCount_decorators;
    var _reviewCount_initializers = [];
    var _reviewCount_extraInitializers = [];
    return _a = /** @class */ (function () {
            function VenueResponseDto() {
                this.id = __runInitializers(this, _id_initializers, void 0);
                this.name = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _name_initializers, void 0));
                this.description = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _description_initializers, void 0));
                this.address = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _address_initializers, void 0));
                this.city = (__runInitializers(this, _address_extraInitializers), __runInitializers(this, _city_initializers, void 0));
                this.province = (__runInitializers(this, _city_extraInitializers), __runInitializers(this, _province_initializers, void 0));
                this.postalCode = (__runInitializers(this, _province_extraInitializers), __runInitializers(this, _postalCode_initializers, void 0));
                this.country = (__runInitializers(this, _postalCode_extraInitializers), __runInitializers(this, _country_initializers, void 0));
                this.latitude = (__runInitializers(this, _country_extraInitializers), __runInitializers(this, _latitude_initializers, void 0));
                this.longitude = (__runInitializers(this, _latitude_extraInitializers), __runInitializers(this, _longitude_initializers, void 0));
                this.type = (__runInitializers(this, _longitude_extraInitializers), __runInitializers(this, _type_initializers, void 0));
                this.capacity = (__runInitializers(this, _type_extraInitializers), __runInitializers(this, _capacity_initializers, void 0));
                this.area = (__runInitializers(this, _capacity_extraInitializers), __runInitializers(this, _area_initializers, void 0));
                this.facilities = (__runInitializers(this, _area_extraInitializers), __runInitializers(this, _facilities_initializers, void 0));
                this.openingHours = (__runInitializers(this, _facilities_extraInitializers), __runInitializers(this, _openingHours_initializers, void 0));
                this.contactPhone = (__runInitializers(this, _openingHours_extraInitializers), __runInitializers(this, _contactPhone_initializers, void 0));
                this.contactEmail = (__runInitializers(this, _contactPhone_extraInitializers), __runInitializers(this, _contactEmail_initializers, void 0));
                this.status = (__runInitializers(this, _contactEmail_extraInitializers), __runInitializers(this, _status_initializers, void 0));
                this.allowOnlineBooking = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _allowOnlineBooking_initializers, void 0));
                this.bookingAdvanceHours = (__runInitializers(this, _allowOnlineBooking_extraInitializers), __runInitializers(this, _bookingAdvanceHours_initializers, void 0));
                this.cancellationPolicy = (__runInitializers(this, _bookingAdvanceHours_extraInitializers), __runInitializers(this, _cancellationPolicy_initializers, void 0));
                this.pricing = (__runInitializers(this, _cancellationPolicy_extraInitializers), __runInitializers(this, _pricing_initializers, void 0));
                this.images = (__runInitializers(this, _pricing_extraInitializers), __runInitializers(this, _images_initializers, void 0));
                this.createdBy = (__runInitializers(this, _images_extraInitializers), __runInitializers(this, _createdBy_initializers, void 0));
                this.ownerId = (__runInitializers(this, _createdBy_extraInitializers), __runInitializers(this, _ownerId_initializers, void 0));
                this.createdAt = (__runInitializers(this, _ownerId_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
                this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
                this.distance = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _distance_initializers, void 0));
                this.averageRating = (__runInitializers(this, _distance_extraInitializers), __runInitializers(this, _averageRating_initializers, void 0));
                this.reviewCount = (__runInitializers(this, _averageRating_extraInitializers), __runInitializers(this, _reviewCount_initializers, void 0));
                __runInitializers(this, _reviewCount_extraInitializers);
                this.id = '';
                this.name = '';
                this.description = null;
                this.address = '';
                this.city = '';
                this.province = '';
                this.postalCode = '';
                this.country = '';
                this.latitude = null;
                this.longitude = null;
                this.type = venue_entity_1.VenueType.OTHER;
                this.capacity = 0;
                this.area = null;
                this.facilities = null;
                this.openingHours = null;
                this.contactPhone = '';
                this.contactEmail = '';
                this.status = venue_entity_1.VenueStatus.ACTIVE;
                this.allowOnlineBooking = false;
                this.bookingAdvanceHours = 0;
                this.cancellationPolicy = null;
                this.pricing = null;
                this.images = null;
                this.createdBy = '';
                this.ownerId = null;
                this.createdAt = new Date();
                this.updatedAt = new Date();
            }
            VenueResponseDto.fromEntity = function (venue) {
                var dto = new _a();
                dto.id = venue.id;
                dto.name = venue.name;
                dto.description = venue.description;
                dto.address = venue.address;
                dto.city = venue.city;
                dto.province = venue.province;
                dto.postalCode = venue.postalCode;
                dto.country = venue.country;
                dto.latitude = venue.latitude;
                dto.longitude = venue.longitude;
                dto.type = venue.type;
                dto.capacity = venue.capacity;
                dto.area = venue.area;
                dto.facilities = venue.facilities;
                dto.openingHours = venue.openingHours;
                dto.contactPhone = venue.contactPhone;
                dto.contactEmail = venue.contactEmail;
                dto.status = venue.status;
                dto.allowOnlineBooking = venue.allowOnlineBooking;
                dto.bookingAdvanceHours = venue.bookingAdvanceHours;
                dto.cancellationPolicy = venue.cancellationPolicy;
                dto.pricing = venue.pricing;
                dto.images = venue.images;
                dto.createdBy = venue.createdBy;
                dto.ownerId = venue.ownerId;
                dto.createdAt = venue.createdAt;
                dto.updatedAt = venue.updatedAt;
                // 虚拟字段
                if (venue.distance !== undefined)
                    dto.distance = venue.distance;
                if (venue.averageRating !== undefined)
                    dto.averageRating = venue.averageRating;
                if (venue.reviewCount !== undefined)
                    dto.reviewCount = venue.reviewCount;
                return dto;
            };
            VenueResponseDto.fromEntities = function (venues) {
                var _this = this;
                return venues.map(function (venue) { return _this.fromEntity(venue); });
            };
            return VenueResponseDto;
        }()),
        (function () {
            var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _id_decorators = [(0, swagger_1.ApiProperty)({ description: '场地ID' })];
            _name_decorators = [(0, swagger_1.ApiProperty)({ description: '场地名称' })];
            _description_decorators = [(0, swagger_1.ApiProperty)({ description: '场地描述', nullable: true })];
            _address_decorators = [(0, swagger_1.ApiProperty)({ description: '场地地址' })];
            _city_decorators = [(0, swagger_1.ApiProperty)({ description: '城市' })];
            _province_decorators = [(0, swagger_1.ApiProperty)({ description: '省份/州' })];
            _postalCode_decorators = [(0, swagger_1.ApiProperty)({ description: '邮政编码' })];
            _country_decorators = [(0, swagger_1.ApiProperty)({ description: '国家' })];
            _latitude_decorators = [(0, swagger_1.ApiProperty)({ description: '纬度', nullable: true })];
            _longitude_decorators = [(0, swagger_1.ApiProperty)({ description: '经度', nullable: true })];
            _type_decorators = [(0, swagger_1.ApiProperty)({ description: '场地类型', enum: venue_entity_1.VenueType })];
            _capacity_decorators = [(0, swagger_1.ApiProperty)({ description: '最大容量' })];
            _area_decorators = [(0, swagger_1.ApiProperty)({ description: '场地面积（平方米）', nullable: true })];
            _facilities_decorators = [(0, swagger_1.ApiProperty)({ description: '设施列表', nullable: true, type: [String] })];
            _openingHours_decorators = [(0, swagger_1.ApiProperty)({ description: '营业时间（JSON格式）', nullable: true })];
            _contactPhone_decorators = [(0, swagger_1.ApiProperty)({ description: '联系方式' })];
            _contactEmail_decorators = [(0, swagger_1.ApiProperty)({ description: '联系邮箱' })];
            _status_decorators = [(0, swagger_1.ApiProperty)({ description: '场地状态', enum: venue_entity_1.VenueStatus })];
            _allowOnlineBooking_decorators = [(0, swagger_1.ApiProperty)({ description: '是否支持在线预订' })];
            _bookingAdvanceHours_decorators = [(0, swagger_1.ApiProperty)({ description: '预订提前时间（小时）' })];
            _cancellationPolicy_decorators = [(0, swagger_1.ApiProperty)({ description: '取消政策（JSON格式）', nullable: true })];
            _pricing_decorators = [(0, swagger_1.ApiProperty)({ description: '价格信息（JSON格式）', nullable: true })];
            _images_decorators = [(0, swagger_1.ApiProperty)({ description: '图片URL列表', nullable: true, type: [String] })];
            _createdBy_decorators = [(0, swagger_1.ApiProperty)({ description: '创建者ID' })];
            _ownerId_decorators = [(0, swagger_1.ApiProperty)({ description: '所有者ID', nullable: true })];
            _createdAt_decorators = [(0, swagger_1.ApiProperty)({ description: '创建时间' })];
            _updatedAt_decorators = [(0, swagger_1.ApiProperty)({ description: '更新时间' })];
            _distance_decorators = [(0, swagger_1.ApiProperty)({ description: '距离（米）', nullable: true })];
            _averageRating_decorators = [(0, swagger_1.ApiProperty)({ description: '平均评分', nullable: true })];
            _reviewCount_decorators = [(0, swagger_1.ApiProperty)({ description: '评论数量', nullable: true })];
            __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
            __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: function (obj) { return "name" in obj; }, get: function (obj) { return obj.name; }, set: function (obj, value) { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
            __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: function (obj) { return "description" in obj; }, get: function (obj) { return obj.description; }, set: function (obj, value) { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
            __esDecorate(null, null, _address_decorators, { kind: "field", name: "address", static: false, private: false, access: { has: function (obj) { return "address" in obj; }, get: function (obj) { return obj.address; }, set: function (obj, value) { obj.address = value; } }, metadata: _metadata }, _address_initializers, _address_extraInitializers);
            __esDecorate(null, null, _city_decorators, { kind: "field", name: "city", static: false, private: false, access: { has: function (obj) { return "city" in obj; }, get: function (obj) { return obj.city; }, set: function (obj, value) { obj.city = value; } }, metadata: _metadata }, _city_initializers, _city_extraInitializers);
            __esDecorate(null, null, _province_decorators, { kind: "field", name: "province", static: false, private: false, access: { has: function (obj) { return "province" in obj; }, get: function (obj) { return obj.province; }, set: function (obj, value) { obj.province = value; } }, metadata: _metadata }, _province_initializers, _province_extraInitializers);
            __esDecorate(null, null, _postalCode_decorators, { kind: "field", name: "postalCode", static: false, private: false, access: { has: function (obj) { return "postalCode" in obj; }, get: function (obj) { return obj.postalCode; }, set: function (obj, value) { obj.postalCode = value; } }, metadata: _metadata }, _postalCode_initializers, _postalCode_extraInitializers);
            __esDecorate(null, null, _country_decorators, { kind: "field", name: "country", static: false, private: false, access: { has: function (obj) { return "country" in obj; }, get: function (obj) { return obj.country; }, set: function (obj, value) { obj.country = value; } }, metadata: _metadata }, _country_initializers, _country_extraInitializers);
            __esDecorate(null, null, _latitude_decorators, { kind: "field", name: "latitude", static: false, private: false, access: { has: function (obj) { return "latitude" in obj; }, get: function (obj) { return obj.latitude; }, set: function (obj, value) { obj.latitude = value; } }, metadata: _metadata }, _latitude_initializers, _latitude_extraInitializers);
            __esDecorate(null, null, _longitude_decorators, { kind: "field", name: "longitude", static: false, private: false, access: { has: function (obj) { return "longitude" in obj; }, get: function (obj) { return obj.longitude; }, set: function (obj, value) { obj.longitude = value; } }, metadata: _metadata }, _longitude_initializers, _longitude_extraInitializers);
            __esDecorate(null, null, _type_decorators, { kind: "field", name: "type", static: false, private: false, access: { has: function (obj) { return "type" in obj; }, get: function (obj) { return obj.type; }, set: function (obj, value) { obj.type = value; } }, metadata: _metadata }, _type_initializers, _type_extraInitializers);
            __esDecorate(null, null, _capacity_decorators, { kind: "field", name: "capacity", static: false, private: false, access: { has: function (obj) { return "capacity" in obj; }, get: function (obj) { return obj.capacity; }, set: function (obj, value) { obj.capacity = value; } }, metadata: _metadata }, _capacity_initializers, _capacity_extraInitializers);
            __esDecorate(null, null, _area_decorators, { kind: "field", name: "area", static: false, private: false, access: { has: function (obj) { return "area" in obj; }, get: function (obj) { return obj.area; }, set: function (obj, value) { obj.area = value; } }, metadata: _metadata }, _area_initializers, _area_extraInitializers);
            __esDecorate(null, null, _facilities_decorators, { kind: "field", name: "facilities", static: false, private: false, access: { has: function (obj) { return "facilities" in obj; }, get: function (obj) { return obj.facilities; }, set: function (obj, value) { obj.facilities = value; } }, metadata: _metadata }, _facilities_initializers, _facilities_extraInitializers);
            __esDecorate(null, null, _openingHours_decorators, { kind: "field", name: "openingHours", static: false, private: false, access: { has: function (obj) { return "openingHours" in obj; }, get: function (obj) { return obj.openingHours; }, set: function (obj, value) { obj.openingHours = value; } }, metadata: _metadata }, _openingHours_initializers, _openingHours_extraInitializers);
            __esDecorate(null, null, _contactPhone_decorators, { kind: "field", name: "contactPhone", static: false, private: false, access: { has: function (obj) { return "contactPhone" in obj; }, get: function (obj) { return obj.contactPhone; }, set: function (obj, value) { obj.contactPhone = value; } }, metadata: _metadata }, _contactPhone_initializers, _contactPhone_extraInitializers);
            __esDecorate(null, null, _contactEmail_decorators, { kind: "field", name: "contactEmail", static: false, private: false, access: { has: function (obj) { return "contactEmail" in obj; }, get: function (obj) { return obj.contactEmail; }, set: function (obj, value) { obj.contactEmail = value; } }, metadata: _metadata }, _contactEmail_initializers, _contactEmail_extraInitializers);
            __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
            __esDecorate(null, null, _allowOnlineBooking_decorators, { kind: "field", name: "allowOnlineBooking", static: false, private: false, access: { has: function (obj) { return "allowOnlineBooking" in obj; }, get: function (obj) { return obj.allowOnlineBooking; }, set: function (obj, value) { obj.allowOnlineBooking = value; } }, metadata: _metadata }, _allowOnlineBooking_initializers, _allowOnlineBooking_extraInitializers);
            __esDecorate(null, null, _bookingAdvanceHours_decorators, { kind: "field", name: "bookingAdvanceHours", static: false, private: false, access: { has: function (obj) { return "bookingAdvanceHours" in obj; }, get: function (obj) { return obj.bookingAdvanceHours; }, set: function (obj, value) { obj.bookingAdvanceHours = value; } }, metadata: _metadata }, _bookingAdvanceHours_initializers, _bookingAdvanceHours_extraInitializers);
            __esDecorate(null, null, _cancellationPolicy_decorators, { kind: "field", name: "cancellationPolicy", static: false, private: false, access: { has: function (obj) { return "cancellationPolicy" in obj; }, get: function (obj) { return obj.cancellationPolicy; }, set: function (obj, value) { obj.cancellationPolicy = value; } }, metadata: _metadata }, _cancellationPolicy_initializers, _cancellationPolicy_extraInitializers);
            __esDecorate(null, null, _pricing_decorators, { kind: "field", name: "pricing", static: false, private: false, access: { has: function (obj) { return "pricing" in obj; }, get: function (obj) { return obj.pricing; }, set: function (obj, value) { obj.pricing = value; } }, metadata: _metadata }, _pricing_initializers, _pricing_extraInitializers);
            __esDecorate(null, null, _images_decorators, { kind: "field", name: "images", static: false, private: false, access: { has: function (obj) { return "images" in obj; }, get: function (obj) { return obj.images; }, set: function (obj, value) { obj.images = value; } }, metadata: _metadata }, _images_initializers, _images_extraInitializers);
            __esDecorate(null, null, _createdBy_decorators, { kind: "field", name: "createdBy", static: false, private: false, access: { has: function (obj) { return "createdBy" in obj; }, get: function (obj) { return obj.createdBy; }, set: function (obj, value) { obj.createdBy = value; } }, metadata: _metadata }, _createdBy_initializers, _createdBy_extraInitializers);
            __esDecorate(null, null, _ownerId_decorators, { kind: "field", name: "ownerId", static: false, private: false, access: { has: function (obj) { return "ownerId" in obj; }, get: function (obj) { return obj.ownerId; }, set: function (obj, value) { obj.ownerId = value; } }, metadata: _metadata }, _ownerId_initializers, _ownerId_extraInitializers);
            __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
            __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
            __esDecorate(null, null, _distance_decorators, { kind: "field", name: "distance", static: false, private: false, access: { has: function (obj) { return "distance" in obj; }, get: function (obj) { return obj.distance; }, set: function (obj, value) { obj.distance = value; } }, metadata: _metadata }, _distance_initializers, _distance_extraInitializers);
            __esDecorate(null, null, _averageRating_decorators, { kind: "field", name: "averageRating", static: false, private: false, access: { has: function (obj) { return "averageRating" in obj; }, get: function (obj) { return obj.averageRating; }, set: function (obj, value) { obj.averageRating = value; } }, metadata: _metadata }, _averageRating_initializers, _averageRating_extraInitializers);
            __esDecorate(null, null, _reviewCount_decorators, { kind: "field", name: "reviewCount", static: false, private: false, access: { has: function (obj) { return "reviewCount" in obj; }, get: function (obj) { return obj.reviewCount; }, set: function (obj, value) { obj.reviewCount = value; } }, metadata: _metadata }, _reviewCount_initializers, _reviewCount_extraInitializers);
            if (_metadata) Object.defineProperty(_a, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        })(),
        _a;
}();
exports.VenueResponseDto = VenueResponseDto;
