/**
 * orders-data.ts — 订单 mock 数据 (ToB 订单管理)
 */

export type OrderStatus = 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
export type OrderPaymentStatus = 'unpaid' | 'paid' | 'partial' | 'refunded';
export type OrderSource = 'manual' | 'api' | 'portal' | 'contract';

export interface OrderItem {
  id: string;
  orderNo: string;
  customerName: string;
  customerCompany: string;
  customerId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  totalAmount: number;
  paidAmount: number;
  status: OrderStatus;
  paymentStatus: OrderPaymentStatus;
  source: OrderSource;
  region: string;
  city: string;
  createdAt: string;
  expectedDelivery: string;
  actualDelivery: string | null;
  salesPerson: string;
  remark: string;
}

export const ORDER_STATUS_MAP: Record<OrderStatus, { label: string; variant: 'success' | 'warning' | 'danger' | 'neutral' | 'info' }> = {
  pending: { label: '待确认', variant: 'neutral' },
  confirmed: { label: '已确认', variant: 'info' },
  processing: { label: '处理中', variant: 'warning' },
  shipped: { label: '已发货', variant: 'success' },
  delivered: { label: '已签收', variant: 'success' },
  cancelled: { label: '已取消', variant: 'danger' },
};

export const ORDER_PAYMENT_STATUS_MAP: Record<OrderPaymentStatus, { label: string; variant: 'success' | 'warning' | 'danger' | 'neutral' }> = {
  unpaid: { label: '未付款', variant: 'danger' },
  paid: { label: '已付款', variant: 'success' },
  partial: { label: '部分付款', variant: 'warning' },
  refunded: { label: '已退款', variant: 'neutral' },
};

export const ORDER_SOURCE_MAP: Record<OrderSource, string> = {
  manual: '手动录入',
  api: 'API导入',
  portal: '门户下单',
  contract: '合同订单',
};

export const ORDER_STATUSES: OrderStatus[] = ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'];
export const ORDER_PAYMENT_STATUSES: OrderPaymentStatus[] = ['unpaid', 'paid', 'partial', 'refunded'];
export const ORDER_SOURCES: OrderSource[] = ['manual', 'api', 'portal', 'contract'];

export const MOCK_ORDERS: OrderItem[] = [
  {
    id: 'ord-001',
    orderNo: 'PO-2026-06-0001',
    customerName: '张伟',
    customerCompany: '云帆科技集团有限公司',
    customerId: 'c-001',
    productName: '旗舰版CRM系统-年度授权',
    quantity: 1,
    unitPrice: 298000,
    totalAmount: 298000,
    paidAmount: 298000,
    status: 'delivered',
    paymentStatus: 'paid',
    source: 'contract',
    region: '华北',
    city: '北京',
    createdAt: '2026-06-01',
    expectedDelivery: '2026-06-10',
    actualDelivery: '2026-06-08',
    salesPerson: '赵一鸣',
    remark: '',
  },
  {
    id: 'ord-002',
    orderNo: 'PO-2026-06-0002',
    customerName: '李芳',
    customerCompany: '星辰连锁超市',
    customerId: 'c-002',
    productName: '门店管理SaaS-50店版',
    quantity: 1,
    unitPrice: 158000,
    totalAmount: 158000,
    paidAmount: 158000,
    status: 'shipped',
    paymentStatus: 'paid',
    source: 'portal',
    region: '华东',
    city: '上海',
    createdAt: '2026-06-05',
    expectedDelivery: '2026-06-15',
    actualDelivery: null,
    salesPerson: '钱丽华',
    remark: '加急处理',
  },
  {
    id: 'ord-003',
    orderNo: 'PO-2026-06-0003',
    customerName: '王强',
    customerCompany: '汇通金融信息有限公司',
    customerId: 'c-003',
    productName: '智能风控系统-企业版',
    quantity: 2,
    unitPrice: 185000,
    totalAmount: 370000,
    paidAmount: 185000,
    status: 'processing',
    paymentStatus: 'partial',
    source: 'api',
    region: '华南',
    city: '深圳',
    createdAt: '2026-06-10',
    expectedDelivery: '2026-06-25',
    actualDelivery: null,
    salesPerson: '孙明阳',
    remark: '分批发货',
  },
  {
    id: 'ord-004',
    orderNo: 'PO-2026-06-0004',
    customerName: '刘洋',
    customerCompany: '博康医疗器械有限公司',
    customerId: 'c-005',
    productName: '医疗物资ERP模块',
    quantity: 3,
    unitPrice: 76000,
    totalAmount: 228000,
    paidAmount: 0,
    status: 'confirmed',
    paymentStatus: 'unpaid',
    source: 'manual',
    region: '西南',
    city: '成都',
    createdAt: '2026-06-12',
    expectedDelivery: '2026-06-28',
    actualDelivery: null,
    salesPerson: '周海波',
    remark: '待财务审核',
  },
  {
    id: 'ord-005',
    orderNo: 'PO-2026-06-0005',
    customerName: '陈军',
    customerCompany: '鼎新制造集团',
    customerId: 'c-006',
    productName: '供应链管理平台-制造版',
    quantity: 1,
    unitPrice: 420000,
    totalAmount: 420000,
    paidAmount: 420000,
    status: 'delivered',
    paymentStatus: 'paid',
    source: 'contract',
    region: '华中',
    city: '武汉',
    createdAt: '2026-05-20',
    expectedDelivery: '2026-06-05',
    actualDelivery: '2026-06-03',
    salesPerson: '赵一鸣',
    remark: '',
  },
  {
    id: 'ord-006',
    orderNo: 'PO-2026-06-0006',
    customerName: '吴杰',
    customerCompany: '华泰金融控股',
    customerId: 'c-009',
    productName: '数据中台-金融专属版',
    quantity: 1,
    unitPrice: 680000,
    totalAmount: 680000,
    paidAmount: 340000,
    status: 'processing',
    paymentStatus: 'partial',
    source: 'contract',
    region: '华北',
    city: '北京',
    createdAt: '2026-06-08',
    expectedDelivery: '2026-07-05',
    actualDelivery: null,
    salesPerson: '孙明阳',
    remark: '分三期付款',
  },
  {
    id: 'ord-007',
    orderNo: 'PO-2026-06-0007',
    customerName: '林琳',
    customerCompany: '仁心医疗科技',
    customerId: 'c-013',
    productName: '远程诊疗系统',
    quantity: 5,
    unitPrice: 45000,
    totalAmount: 225000,
    paidAmount: 225000,
    status: 'shipped',
    paymentStatus: 'paid',
    source: 'portal',
    region: '华中',
    city: '长沙',
    createdAt: '2026-06-14',
    expectedDelivery: '2026-06-22',
    actualDelivery: null,
    salesPerson: '钱丽华',
    remark: '',
  },
  {
    id: 'ord-008',
    orderNo: 'PO-2026-06-0008',
    customerName: '黄磊',
    customerCompany: '阳光教育集团',
    customerId: 'c-011',
    productName: '智慧校园SaaS-标准版',
    quantity: 10,
    unitPrice: 12800,
    totalAmount: 128000,
    paidAmount: 0,
    status: 'pending',
    paymentStatus: 'unpaid',
    source: 'manual',
    region: '华中',
    city: '郑州',
    createdAt: '2026-06-18',
    expectedDelivery: '2026-07-02',
    actualDelivery: null,
    salesPerson: '周海波',
    remark: '报价审核中',
  },
  {
    id: 'ord-009',
    orderNo: 'PO-2026-06-0009',
    customerName: '马超',
    customerCompany: '远见零售管理',
    customerId: 'c-014',
    productName: '零售数据分析模块',
    quantity: 2,
    unitPrice: 35000,
    totalAmount: 70000,
    paidAmount: 0,
    status: 'cancelled',
    paymentStatus: 'unpaid',
    source: 'portal',
    region: '华东',
    city: '青岛',
    createdAt: '2026-06-02',
    expectedDelivery: '2026-06-16',
    actualDelivery: null,
    salesPerson: '钱丽华',
    remark: '客户取消订单',
  },
  {
    id: 'ord-010',
    orderNo: 'PO-2026-06-0010',
    customerName: '孙浩',
    customerCompany: '天翼信息技术有限公司',
    customerId: 'c-008',
    productName: '云运维监控平台',
    quantity: 1,
    unitPrice: 96000,
    totalAmount: 96000,
    paidAmount: 96000,
    status: 'delivered',
    paymentStatus: 'paid',
    source: 'manual',
    region: '华东',
    city: '杭州',
    createdAt: '2026-05-28',
    expectedDelivery: '2026-06-08',
    actualDelivery: '2026-06-06',
    salesPerson: '赵一鸣',
    remark: '',
  },
  {
    id: 'ord-011',
    orderNo: 'PO-2026-06-0011',
    customerName: '郑洁',
    customerCompany: '碧源环保科技',
    customerId: 'c-010',
    productName: '环境监测数据平台',
    quantity: 1,
    unitPrice: 85000,
    totalAmount: 85000,
    paidAmount: 85000,
    status: 'pending',
    paymentStatus: 'paid',
    source: 'api',
    region: '西北',
    city: '西安',
    createdAt: '2026-06-20',
    expectedDelivery: '2026-07-10',
    actualDelivery: null,
    salesPerson: '孙明阳',
    remark: '预付款已到账',
  },
  {
    id: 'ord-012',
    orderNo: 'PO-2026-06-0012',
    customerName: '韩雪',
    customerCompany: '创云软件开发',
    customerId: 'c-015',
    productName: 'DevOps平台-团队版',
    quantity: 1,
    unitPrice: 72000,
    totalAmount: 72000,
    paidAmount: 72000,
    status: 'confirmed',
    paymentStatus: 'paid',
    source: 'portal',
    region: '东南',
    city: '厦门',
    createdAt: '2026-06-15',
    expectedDelivery: '2026-06-29',
    actualDelivery: null,
    salesPerson: '周海波',
    remark: '',
  },
];
