apiVersion: v1
kind: Secret
metadata:
  name: __TLS_SECRET_NAME__
  namespace: m5
  labels:
    app.kubernetes.io/part-of: shenjiying
type: kubernetes.io/tls
data:
  tls.crt: "__TLS_CERT_B64__"
  tls.key: "__TLS_KEY_B64__"
