/**
 * products-data.ts — Products mock data for admin-web list page
 */

export type ProductStatus = 'active' | 'inactive' | 'discontinued' | 'draft';
export type ProductCategory = 'food' | 'beverage' | 'daily' | 'electronics' | 'clothing' | 'other';

export interface ProductItem {
  id: string;
  sku: string;
  name: string;
  category: ProductCategory;
  price: number;
  cost: number;
  stock: number;
  unit: string;
  status: ProductStatus;
  brandName: string;
  marketCode: string;
  storeName: string;
  createdAt: string;
  updatedAt: string;
}

export const PRODUCT_STATUS_MAP: Record<ProductStatus, { label: string; variant: 'success' | 'warning' | 'danger' | 'neutral' }> = {
  active: { label: '在售', variant: 'success' },
  inactive: { label: '下架', variant: 'warning' },
  discontinued: { label: '停产', variant: 'danger' },
  draft: { label: '草稿', variant: 'neutral' },
};

export const PRODUCT_CATEGORY_MAP: Record<ProductCategory, { label: string; variant: 'success' | 'warning' | 'danger' | 'neutral' | 'info' }> = {
  food: { label: '食品', variant: 'success' },
  beverage: { label: '饮料', variant: 'info' },
  daily: { label: '日用品', variant: 'neutral' },
  electronics: { label: '电子', variant: 'warning' },
  clothing: { label: '服装', variant: 'info' },
  other: { label: '其他', variant: 'neutral' },
};

export const PRODUCT_STATUSES: ProductStatus[] = ['active', 'inactive', 'discontinued', 'draft'];
export const PRODUCT_CATEGORIES: ProductCategory[] = ['food', 'beverage', 'daily', 'electronics', 'clothing', 'other'];

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    id: 'p-001',
    sku: 'SKU-10001',
    name: '有机全麦面包',
    category: 'food',
    price: 18.50,
    cost: 12.30,
    stock: 245,
    unit: '个',
    status: 'active',
    brandName: '健康烘焙坊',
    marketCode: 'CN-BJ',
    storeName: '朝阳旗舰店',
    createdAt: '2025-01-15',
    updatedAt: '2026-06-10',
  },
  {
    id: 'p-002',
    sku: 'SKU-10002',
    name: '无糖绿茶饮料 500ml',
    category: 'beverage',
    price: 6.00,
    cost: 3.80,
    stock: 1520,
    unit: '瓶',
    status: 'active',
    brandName: '清泉饮品',
    marketCode: 'CN-BJ',
    storeName: '朝阳旗舰店',
    createdAt: '2025-02-20',
    updatedAt: '2026-06-12',
  },
  {
    id: 'p-003',
    sku: 'SKU-10003',
    name: '竹纤维洗碗布 3片装',
    category: 'daily',
    price: 12.90,
    cost: 7.50,
    stock: 89,
    unit: '包',
    status: 'active',
    brandName: '绿居家',
    marketCode: 'CN-SH',
    storeName: '浦东生活馆',
    createdAt: '2025-03-01',
    updatedAt: '2026-06-08',
  },
  {
    id: 'p-004',
    sku: 'SKU-10004',
    name: '蓝牙降噪耳机 Pro',
    category: 'electronics',
    price: 499.00,
    cost: 320.00,
    stock: 56,
    unit: '台',
    status: 'active',
    brandName: '声学科技',
    marketCode: 'CN-SH',
    storeName: '浦东生活馆',
    createdAt: '2025-01-10',
    updatedAt: '2026-06-14',
  },
  {
    id: 'p-005',
    sku: 'SKU-10005',
    name: '纯棉短袖T恤 男女同款',
    category: 'clothing',
    price: 89.00,
    cost: 45.00,
    stock: 320,
    unit: '件',
    status: 'active',
    brandName: '舒适棉品',
    marketCode: 'CN-GZ',
    storeName: '天河购物中心',
    createdAt: '2025-04-15',
    updatedAt: '2026-06-11',
  },
  {
    id: 'p-006',
    sku: 'SKU-10006',
    name: '手工曲奇饼干礼盒',
    category: 'food',
    price: 68.00,
    cost: 40.00,
    stock: 0,
    unit: '盒',
    status: 'inactive',
    brandName: '甜蜜烘焙屋',
    marketCode: 'CN-BJ',
    storeName: '西城分店',
    createdAt: '2025-05-01',
    updatedAt: '2026-05-28',
  },
  {
    id: 'p-007',
    sku: 'SKU-10007',
    name: '椰子水 330ml × 6',
    category: 'beverage',
    price: 28.00,
    cost: 18.50,
    stock: 430,
    unit: '箱',
    status: 'active',
    brandName: '热带果园',
    marketCode: 'CN-GZ',
    storeName: '天河购物中心',
    createdAt: '2025-03-20',
    updatedAt: '2026-06-13',
  },
  {
    id: 'p-008',
    sku: 'SKU-10008',
    name: 'USB-C 快充数据线 2m',
    category: 'electronics',
    price: 39.90,
    cost: 22.00,
    stock: 180,
    unit: '根',
    status: 'active',
    brandName: '充电先锋',
    marketCode: 'CN-SH',
    storeName: '静安数码港',
    createdAt: '2025-02-28',
    updatedAt: '2026-06-09',
  },
  {
    id: 'p-009',
    sku: 'SKU-10009',
    name: '抗菌洗手液 500ml',
    category: 'daily',
    price: 15.80,
    cost: 9.20,
    stock: 512,
    unit: '瓶',
    status: 'active',
    brandName: '洁美家',
    marketCode: 'CN-BJ',
    storeName: '朝阳旗舰店',
    createdAt: '2025-06-10',
    updatedAt: '2026-06-12',
  },
  {
    id: 'p-010',
    sku: 'SKU-10010',
    name: '冬季保暖羽绒马甲',
    category: 'clothing',
    price: 259.00,
    cost: 150.00,
    stock: 15,
    unit: '件',
    status: 'discontinued',
    brandName: '温暖行',
    marketCode: 'CN-GZ',
    storeName: '天河购物中心',
    createdAt: '2024-11-01',
    updatedAt: '2026-06-01',
  },
  {
    id: 'p-011',
    sku: 'SKU-10011',
    name: '有机豆浆粉 无糖',
    category: 'food',
    price: 32.00,
    cost: 20.00,
    stock: 178,
    unit: '袋',
    status: 'draft',
    brandName: '豆本真',
    marketCode: 'CN-SH',
    storeName: '浦东生活馆',
    createdAt: '2026-05-20',
    updatedAt: '2026-06-13',
  },
  {
    id: 'p-012',
    sku: 'SKU-10012',
    name: '矿泉气泡水 柠檬味',
    category: 'beverage',
    price: 4.50,
    cost: 2.80,
    stock: 3000,
    unit: '瓶',
    status: 'active',
    brandName: '山泉饮品',
    marketCode: 'CN-BJ',
    storeName: '西城分店',
    createdAt: '2025-04-01',
    updatedAt: '2026-06-14',
  },
  {
    id: 'p-013',
    sku: 'SKU-10013',
    name: '智能体重秤 WiFi版',
    category: 'electronics',
    price: 149.00,
    cost: 95.00,
    stock: 42,
    unit: '台',
    status: 'active',
    brandName: '健康科技',
    marketCode: 'CN-SH',
    storeName: '静安数码港',
    createdAt: '2025-03-15',
    updatedAt: '2026-06-10',
  },
  {
    id: 'p-014',
    sku: 'SKU-10014',
    name: '薰衣草洗衣液 2L',
    category: 'daily',
    price: 29.90,
    cost: 18.00,
    stock: 0,
    unit: '瓶',
    status: 'inactive',
    brandName: '花香坊',
    marketCode: 'CN-GZ',
    storeName: '天河购物中心',
    createdAt: '2025-05-10',
    updatedAt: '2026-06-05',
  },
  {
    id: 'p-015',
    sku: 'SKU-10015',
    name: '速干运动长裤',
    category: 'clothing',
    price: 169.00,
    cost: 95.00,
    stock: 88,
    unit: '条',
    status: 'active',
    brandName: '动感衣橱',
    marketCode: 'CN-BJ',
    storeName: '朝阳旗舰店',
    createdAt: '2025-06-01',
    updatedAt: '2026-06-12',
  },
];
