apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-m5
  labels:
    app.kubernetes.io/part-of: shenjiying
    app.kubernetes.io/component: cert-manager
spec:
  acme:
    email: yaoyunzhong@sportantmeta.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-m5-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.sportsant.net
            solverName: alidns
            config:
              region: cn-hangzhou
              accessKeyIdRef:
                name: alidns-credentials
                key: access-key-id
              accessKeySecretRef:
                name: alidns-credentials
                key: access-key-secret
