/**
 * Robots.txt 动态配置API
 */

import { NextResponse } from 'next/server';

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'https://www.shenjiying.com';

export async function GET() {
  const robotsTxt = `# Robots.txt for ${BASE_URL}
# Generated by SEO System at ${new Date().toISOString()}

User-agent: *
Allow: /

# Disallow admin and private paths
Disallow: /admin/
Disallow: /api/
Disallow: /_next/
Disallow: /monitoring

# Sitemap
Sitemap: ${BASE_URL}/sitemap.xml

# Crawl-delay for polite crawling
Crawl-delay: 1

# Baidu Bot
User-agent: Baiduspider
Allow: /
Crawl-delay: 2

# Google Bot
User-agent: Googlebot
Allow: /
Crawl-delay: 1

# Bing Bot
User-agent: Bingbot
Allow: /
Crawl-delay: 1

# Sogou Bot
User-agent: Sogou Spider
Allow: /
Crawl-delay: 5

# Bytespider
User-agent: Bytespider
Disallow: /

# Twitter Bot
User-agent: Twitterbot
Allow: /

# Facebook Bot
User-agent: Facebot
Allow: /
`;

  return new NextResponse(robotsTxt, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      'Cache-Control': 'public, max-age=86400',
    },
  });
}
